# /etc/nic.conf — nic network configuration
# Lines starting with # are comments
# See: nic show, nic dry-run

# Load Sowa's default IPv4 and IPv6 policies transactionally with the network.
iptables /etc/nic.rules.v4
ip6tables /etc/nic.rules.v6

up eth0
dhcp eth0

#ns 1.1.1.1
#ns 1.0.0.1
#ns 2606:4700:4700::1111
#ns 2606:4700:4700::1001

# Include additional config files (loaded in alphanumeric / natural order)
include nic.d/*.conf
