#!/usr/bin/env bash
#
# Pack sowa-setup, sowa-bootstrap, sowa-chroot and the library all three source
# into one file that can be carried to a machine with no Sowa on it.
#
# The image ships those as four files under /usr/lib and /usr/sbin, which is the
# right shape for a system that has them installed and the wrong shape for the
# job they are most needed for: installing Sowa from a hosting provider's
# rescue environment or another host where none of the files are installed.
# Four files that have to land at four absolute paths before the first one will
# start is not something to talk a person through.
#
# The four are embedded verbatim, each in its own quoted here-document, and
# written back out to a private temporary directory at run time. Verbatim
# matters: the bundle is then provably the same program as the one in the image
# rather than a second copy that has to be kept in step, and it stays a text
# file that can be read with less(1), which a base64 blob would not.
#
# What makes this possible at all is that the three programs find their library
# through ${SOWA_INSTALL_LIB} rather than at a fixed /usr/lib/sowa - the one
# change needed to make them relocatable, and the reason there is no rewriting
# step here.

set -Eeuo pipefail
# shellcheck source=lib/common.sh
source "$(dirname "$0")/lib/common.sh"

readonly OVERLAY="${PROJECT_ROOT}/rootfs-overlay"
readonly LIBRARY="${OVERLAY}/usr/lib/sowa/install-functions"
readonly PROGRAMS=(sowa-setup sowa-bootstrap sowa-chroot)

# The here-document delimiter. It has to be a line that appears in none of the
# payloads, which is checked rather than assumed: a payload containing it would
# end its own here-document early and produce a bundle that is silently a
# truncated program.
readonly DELIMITER='__SOWA_INSTALL_PAYLOAD__'

mkdir -p "${ARTIFACT_DIR}"
bundle="${ARTIFACT_DIR}/sowa-install"

# The minimum kernel named in the generated header is read out of the library
# rather than written here, so the number in the documentation cannot drift away
# from the number in the check.
minimum_kernel() {
    local major minor
    major="$(sed -n 's/^readonly SOWA_MIN_KERNEL_MAJOR=\([0-9]*\)$/\1/p' "${LIBRARY}")"
    minor="$(sed -n 's/^readonly SOWA_MIN_KERNEL_MINOR=\([0-9]*\)$/\1/p' "${LIBRARY}")"
    [[ -n "${major}" && -n "${minor}" ]] \
        || die "cannot read the minimum kernel version out of ${LIBRARY}"
    printf '%s.%s\n' "${major}" "${minor}"
}
temporary="${bundle}.tmp.$$"
trap 'rm -f "${temporary}"' EXIT

[[ -f "${LIBRARY}" ]] || die "the installer library is missing: ${LIBRARY}"
for program in "${PROGRAMS[@]}"; do
    [[ -f "${OVERLAY}/usr/sbin/${program}" ]] \
        || die "${program} is missing from the overlay"
done

# Each program has to reach its library through the variable, or the bundle
# would unpack four files and then watch three of them read /usr/lib/sowa
# instead - which is absent outside an installed Sowa system and is the whole
# bug this exists to close.
for program in "${PROGRAMS[@]}"; do
    # shellcheck disable=SC2016 # matching the literal text, not expanding it
    grep -q '^source "\${SOWA_INSTALL_LIB:-/usr/lib/sowa}/install-functions"$' \
        "${OVERLAY}/usr/sbin/${program}" \
        || die "${program} does not source its library through SOWA_INSTALL_LIB; it cannot be bundled"
done

emit_payload() {
    local destination="$1" source_file="$2"
    grep -qxF "${DELIMITER}" "${source_file}" \
        && die "${source_file} contains the here-document delimiter; the bundle would be truncated"
    # shellcheck disable=SC2016 # ${directory} is expanded by the generated
    # bundle when it runs, which is exactly why it is written literally here
    printf 'cat > "${directory}/%s" <<'\''%s'\''\n' "${destination}" "${DELIMITER}"
    cat "${source_file}"
    printf '%s\n' "${DELIMITER}"
}

kernel_floor="$(minimum_kernel)"
log "create ${bundle}"

{
    cat <<HEADER
#!/bin/bash
#
# sowa-install - install Sowa Linux from a system that is not Sowa.
#
# This is sowa-setup, sowa-bootstrap and sowa-chroot in one file, generated by
# scripts/make-installer-bundle.sh from ${DISTRO_NAME} ${DISTRO_VERSION}. The three
# programs are embedded below exactly as the image ships them; this script
# unpacks them into a temporary directory, runs the one asked for, and removes
# them again.
#
#   sowa-install bootstrap --from-tarball ${DISTRO_NAME}-${DISTRO_VERSION}-${ARTIFACT_ARCH}-rootfs.tar.xz /mnt
#   sowa-install chroot /mnt grub-install --target=i386-pc /dev/sda
#   sowa-install chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
#   sowa-install setup /dev/sda
#
# 'bootstrap' installs into a filesystem you have already mounted and leaves the
# partitioning and the boot loader to you. 'chroot' enters the result with
# /proc, /sys, /dev and /run in place, which is what grub-install and
# grub-mkconfig need to work. 'setup' partitions and installs a whole disk on
# its own, and only works when run from a booted Sowa system, since it copies
# the running root.
#
# Outside a running Sowa system, 'bootstrap --from-tarball' is the one to use:
# there is no live Sowa root to copy, so the rootfs tarball is the source.
#
# It needs bash, tar, xz and root. It requires Linux ${kernel_floor} or newer, and
# says so rather than half-working, because Sowa's binaries are built against a
# glibc that assumes it.

set -Eeuo pipefail

readonly SOWA_INSTALL_DISTRO_VERSION="${DISTRO_VERSION}"
HEADER

    cat <<'BODY'

usage() {
    printf 'usage: %s COMMAND [ARGUMENT...]\n\n' "${0##*/}"
    printf 'Commands:\n'
    printf '  bootstrap   install into a filesystem you have already mounted\n'
    printf '  chroot      enter an installed Sowa system with /proc, /sys, /dev, /run\n'
    printf '  setup       partition and install a whole disk (from a booted Sowa only)\n'
    printf '  version     print the version this bundle was made from\n\n'
    printf 'Each command takes the arguments of the program it runs; pass --help\n'
    printf 'after the command to see them:\n\n'
    printf '  %s bootstrap --help\n\n' "${0##*/}"
    printf 'Portable installation onto a disk, start to finish:\n\n'
    printf '  %s bootstrap --from-tarball sowa-rootfs.tar.xz /mnt\n' "${0##*/}"
    printf '  %s chroot /mnt grub-install --target=i386-pc /dev/sda\n' "${0##*/}"
    printf '  %s chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg\n' "${0##*/}"
    exit "${1:-1}"
}

# The four files, written back out as they are in the image. The caller owns the
# directory and removes it; nothing here outlives the run.
unpack() {
    local directory="$1"
    mkdir -p "${directory}/lib" "${directory}/sbin"
BODY

    emit_payload "lib/install-functions" "${LIBRARY}"
    for program in "${PROGRAMS[@]}"; do
        emit_payload "sbin/${program}" "${OVERLAY}/usr/sbin/${program}"
    done

    cat <<'BODY'
    chmod 0755 "${directory}"/sbin/*
}

main() {
    local command="${1:-}"
    case "${command}" in
        setup | bootstrap | chroot) shift ;;
        -h | --help | help | '') usage 0 ;;
        -V | --version | version)
            printf 'sowa-install (Sowa Linux) %s\n' "${SOWA_INSTALL_DISTRO_VERSION}"
            exit 0 ;;
        *)
            printf 'error: unknown command: %s\n\n' "${command}" >&2
            usage 1 ;;
    esac

    command -v tar >/dev/null 2>&1 || { printf 'error: tar is required\n' >&2; exit 1; }

    local directory
    directory="$(mktemp -d "${TMPDIR:-/tmp}/sowa-install.XXXXXX")" \
        || { printf 'error: cannot create a temporary directory\n' >&2; exit 1; }
    trap 'rm -rf "${directory}"' EXIT
    unpack "${directory}"

    # The programs are run rather than sourced, so each keeps its own set -e,
    # its own traps and its own exit status - and that status is this script's.
    # SOWA_INSTALL_LIB is what points them at the library beside them instead of
    # at an /usr/lib/sowa that is not present on this host.
    # bootstrap finishes by printing the two sowa-chroot commands that follow it.
    # "sowa-chroot" is not a command on a machine that has no Sowa installed, and
    # the copy this bundle unpacked is deleted on the way out, so tell it to
    # print the way back in to this script instead - by absolute path, since the
    # instructions outlive the shell's working directory.
    local self="${0}"
    case "${self}" in
        /*) ;;
        *) self="${PWD}/${self#./}" ;;
    esac

    local status=0
    SOWA_INSTALL_LIB="${directory}/lib" \
    SOWA_INSTALL_CHROOT_COMMAND="${self} chroot" \
        "${directory}/sbin/sowa-${command}" "$@" || status=$?
    exit "${status}"
}

main "$@"
BODY
} > "${temporary}"

chmod 0755 "${temporary}"

# A bundle that does not parse is worse than none: it would be carried to the
# machine that has no other copy of these programs before anything found out.
bash -n "${temporary}" || die "the generated bundle is not valid bash"

# And one that carries something other than what went in is the failure the
# delimiter check exists to prevent, so prove it rather than trust it. The
# payloads are read back out of the finished file as text - not by running it -
# so this checks what a person would see in an editor, and cannot be fooled by
# the bundle's own code being wrong in the same direction twice.
payload_of() {
    local name="$1"
    awk -v want="cat > \"\${directory}/${name}\" <<'${DELIMITER}'" -v delimiter="${DELIMITER}" '
        $0 == want { inside = 1; next }
        inside && $0 == delimiter { exit }
        inside { print }
    ' "${temporary}"
}

verify_payload() {
    local name="$1" original="$2"
    diff -q <(payload_of "${name}") "${original}" >/dev/null \
        || die "the bundled ${name} does not match ${original}"
}

verify_payload "lib/install-functions" "${LIBRARY}"
for program in "${PROGRAMS[@]}"; do
    verify_payload "sbin/${program}" "${OVERLAY}/usr/sbin/${program}"
done

mv "${temporary}" "${bundle}"
trap - EXIT
write_sha256_manifest "${bundle}"
log "bundled ${PROGRAMS[*]} and install-functions into ${bundle}"
